### ISSUE TITLE
calendar for TaskFolder

### ISSUE THREAD

**Issue by okiochan** [okiochan/organizer#64]
DialogAddFolder now has a calendar

![2018-09-14_14-13-22](https://user-images.githubusercontent.com/32464760/45547162-753dff00-b828-11e8-9115-c6a17a084b96.png)

add method that saves start , end date for TaskFolder

**Comment by FeastyPets** [comment]
transfer calendars to tasks, not task folders

**Comment by okiochan** [comment]
done, continue to work =)

**Comment by FeastyPets** [comment]
done in latest trunk
